### ISSUE TITLE
DFV Data - Inconsistency in Geographic Codes

### ISSUE THREAD

**Issue by pwisniewski-econ** [pwisEcon/interestnpy#1]
### Description
I've noticed an inconsistency in the 2019 DVF dataset regarding the geographic coding of a few municipalities, which represents in total 200-300 transactions. For example, it appears that Courcouronnes still uses its original CODGEO (91182), even after its merger with Evry in 2019. This issue can be observed by looking into the NA values left in the aggregated tables.

#### Step 1: Identify the Impact
- Identify the number of cities/towns/EPCI impacted by this problem per year.

#### Step 2: Address the Issue
- **Options**:
  1. Add custom entries in our "table de passage" for the biggest cities wrongly identified.
  2. Alternatively, simply remove those observations from the dataset.

**Comment by RemiCSK** [comment]
After investigation I found out that there were not that much cities with this problem and the number of concerned transactions is relatively low. So I suggest to filter the problematic lines out. You can check the cities etc in [codgeo_nan_investigation.py]. The code is a little bit long to run so here is the most important output:

Number of commune with nan for CODGEO in 2023 : 5, total number transactions with nan for CODGEO this year : 15
Number of commune with nan for CODGEO in 2022 : 4, total number transactions with nan for CODGEO this year : 73
Number of commune with nan for CODGEO in 2021 : 4, total number transactions with nan for CODGEO this year : 42
Number of commune with nan for CODGEO in 2020 : 0, total number transactions with nan for CODGEO this year : 0 
Number of commune with nan for CODGEO in 2019 : 135, total number transactions with nan for CODGEO this year : 604
Number of commune with nan for CODGEO in 2018 : 16, total number transactions with nan for CODGEO this year : 36
Number of commune with nan for CODGEO in 2017 : 48, total number transactions with nan for CODGEO this year : 189
Number of commune with nan for CODGEO in 2016 : 395, total number transactions with nan for CODGEO this year : 1602
Number of commune with nan for CODGEO in 2015 : 11, total number transactions with nan for CODGEO this year : 58
Number of commune with nan for CODGEO in 2014 : 0, total number transactions with nan for CODGEO this year : 0
