### ISSUE TITLE
Problem with popdensity2019 ?

### ISSUE THREAD

**Issue by RemiCSK** [pwisEcon/interestnpy#16]
In the notebook  in control variables it is written 
densite["popdensity2019"] = densite["P20_POP"] / densite["SUPERF"]

Shouldn't we divide the population of 2019 instead of 2020 ?

**Comment by pwisniewski-econ** [comment]
Yeah the name should be corrected, it's not "popdensity2019" but popdensity2020, good catch!
From what I saw, data from 2019 is not part of the main INSEE population study, its from a continuous "enquete". The "clean" data is available for 2014 and 2020.

**Comment by pwisniewski-econ** [comment]
Fixed in the notebook, will not fix in scripts.
