### ISSUE TITLE
Creation of Control Variables Tables

### ISSUE THREAD

**Issue by pwisniewski-econ** [pwisEcon/interestnpy#3]
### Objective
Develop comprehensive tables containing aggregated control variables for towns (COM) and Zone d'Emploi (see issue #2) spanning from 2014 to 2023. 

### Data Extrapolation
- Utilize national trends and/or simple linear models for extrapolation when direct data is not available for a given year.

### Control Variables
The following variables should be included in the tables:
1. Unemployment
2. Revenues
3. Population Density
4. Firms Density
5. Number of Schools per Capita
6. Number of Primary Care Physicians per Capita
7. Drug Trafficking Rate
8. Assaults Rate
9. Burglary Rate

Feel free to add additional variables. 

### Table Format
- **Expected Output**: Two separate tables, one for each level (COM [IDENT] and ZE [IDENT_ROBUST]).
- **Structure**:
  - Columns: ID, DATE, VAR1, VAR2, ..., VARN
  - Example Rows:
    - 01 - 01/01/2014 - ...
    - 01 - 01/07/2014 - ...
    - 01 - 01/01/2015 - ...

### Code Adaptability
- **Requirement**: The code used to generate these tables should be easily adaptable for quarterly data, in case this decision is made in the future.

### Further Instructions
- Ensure accuracy and consistency in data aggregation and extrapolation.
- Maintain clear documentation for methodologies used in data processing.

I look forward to seeing the implementation of these tables, which will be crucial for our analysis. Please feel free to reach out if there are any questions or need for clarification.

**Comment by pwisniewski-econ** [comment]
We had a discussion with @lu-julia, the data availability for periods after 2020, is quite poor and many variables don't vary much between the years (e.g. density), so I think we'll stick with a few constant characteristics (for let's say 2019) and a growth rate (let's say 2014-2019) which we'll use to estimate a non fixed effect model (maybe a random effects one)..

We then don't measure any of the covid effects but that's the charm of working with public data!

**Comment by pwisniewski-econ** [comment]
So we could have this structure
ID, REVENUES_2019, REVENUES_GROWTH, DENSITY, DENSITY_GROWTH, etc...
01, 27000, .......
02, 15000, .......

As you can see the work you did was useful to compute growth rates!

**Comment by pwisniewski-econ** [comment]
Any progress? @RemiCSK @lu-julia

**Comment by RemiCSK** [comment]
> Any progress? @RemiCSK @lu-julia

Unemployment and income is done. I will do population density, criminality and number of physicians. May eventually need help later on to use the table de passage.
